name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ftp.rafaeldutradev.com.br
        user: rafaeldutradev1
        password: Rafinha@25051991
        remoteDir: public_html/rdi
        localDir: .

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit e Push dos arquivos
        run: |
          git add .
          git commit -m "Atualizando arquivos do FTP"
          git push origin main
