name: Deploy via FTP

on:
  push:
    branches:
      - main  # Dispara o deploy ao fazer push na branch main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}      # Nome ou IP do servidor FTP
          username: ${{ secrets.FTP_USER }}      # Usuário FTP
          password: ${{ secrets.FTP_PASS }}      # Senha FTP
          local-dir: ./                          # Diretório local (raiz do repositório)
          server-dir: /public_html/              # Diretório remoto no servidor FTP
          port: 21                               # Porta do FTP (padrão é 21)
