name: Deploy via FTP

on:
  push:
    branches:
      - main  # Ou a branch que deseja usar

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "."  # Enviar todos os arquivos do repositório
          remoteDir: "public_html"  # Diretório raiz do servidor (ou "/" se for permitido)
          forceSsl: false
