name: Deploy via FTP

on:
  push:
    branches:
      - main  # ou a branch que você deseja usar

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}  # ftp.rafaeldutradev.com.br
          user: ${{ secrets.USER }}  # rafaeldutradev1
          password: ${{ secrets.PASS }}  # Rafinha@25051991
          localDir: "dist"  # O diretório local que contém os arquivos para enviar (substitua conforme necessário)
          remoteDir: "/files/public_html/rdi/"  # Diretório remoto no servidor FTP
          port: 21  # Porta do FTP (você indicou ser 21)
