name: Deploy via FTP

on:
  push:
    branches:
      - main  # ou a branch que você deseja usar

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}  
          user: ${{ secrets.USER }} 
          password: ${{ secrets.PASS }}  
          localDir: "."  # O diretório local que contém os arquivos para enviar (substitua conforme necessário)
          remoteDir: "/files/public_html/rdi/"  # Diretório remoto no servidor FTP
         
