name: Deploy via FTP

on:
  push:
    branches:
      - main  # Define a branch que acionará o deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}  # Configure no GitHub Secrets
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./  # Todos os arquivos do repositório
          server-dir: /public_html/  # Diretório do servidor onde os arquivos serão enviados
